index:
    path: /
    controller: App\Controller\DefaultController::index
search:
    path: /search
    controller: App\Controller\DefaultController::search
hotel:
    path: /hotel/{id}
    controller: App\Controller\HotelController::showHotel
searchresult:
    path: /searchresult
    controller: App\Controller\DefaultController::showSearchResult
register:
    path: /register
    controller: App\Controller\RefistrationController::register
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
checkout:
    path: /checkout/{id}
    controller: App\Controller\HotelController::checkoutHotel
cabinet:
    path: /cabinet
    controller: App\Controller\DefaultController::showCabinet
addHotel:
    path: /addHotel
    controller: App\Controller\HotelController::addHotel
deleteHotel:
    path: /deleteHotel/{id}
    controller: App\Controller\HotelController::deleteHotel

