index:
    path: /
    controller: App\Controller\DefaultController::index
search:
    path: /search
    controller: App\Controller\DefaultController::search
hotel:
    path: /hotel/{id}
    controller: App\Controller\HotelController::showHotel
register:
    path: /register
    controller: App\Controller\RefistrationController::register
login:
    path: /login
    controller: App\Controller\SecurityController::login

